// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ytW6RxmNe0_xO-LpfTvNSvCtnkI3WeY',
    appId: '1:463874956038:web:edc41337b83306042d1c87',
    messagingSenderId: '463874956038',
    projectId: 'al-majd-motors',
    authDomain: 'al-majd-motors.firebaseapp.com',
    storageBucket: 'al-majd-motors.firebasestorage.app',
    measurementId: 'G-WXNRL92DFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7W4FeLEEu_msWPlXEtzRYEWPY-OpAd4',
    appId: '1:463874956038:android:3d14e18b69f3965c2d1c87',
    messagingSenderId: '463874956038',
    projectId: 'al-majd-motors',
    storageBucket: 'al-majd-motors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrtvFTcF7yHxs6k-NxzgFbd1u6BIHoNgA',
    appId: '1:463874956038:ios:5546ade5f27d8f562d1c87',
    messagingSenderId: '463874956038',
    projectId: 'al-majd-motors',
    storageBucket: 'al-majd-motors.firebasestorage.app',
    iosBundleId: 'com.example.carsECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrtvFTcF7yHxs6k-NxzgFbd1u6BIHoNgA',
    appId: '1:463874956038:ios:5546ade5f27d8f562d1c87',
    messagingSenderId: '463874956038',
    projectId: 'al-majd-motors',
    storageBucket: 'al-majd-motors.firebasestorage.app',
    iosBundleId: 'com.example.carsECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ytW6RxmNe0_xO-LpfTvNSvCtnkI3WeY',
    appId: '1:463874956038:web:9dcde5b26dfa88432d1c87',
    messagingSenderId: '463874956038',
    projectId: 'al-majd-motors',
    authDomain: 'al-majd-motors.firebaseapp.com',
    storageBucket: 'al-majd-motors.firebasestorage.app',
    measurementId: 'G-K1XLBR1ZWK',
  );
}
